### ISSUE TITLE
gethealthがJSONDecodeErrorになることがある

### ISSUE THREAD

**Issue by mayabaha** [mayabaha/vcts#6]
scalpingモジュールでbitflyerの取引所ステータスを取得する際、以下のエラーが出ることがある

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/export/takashi/Documents/vcts/scalping.py", line 200, in runscalp
    status = self.bfpublic.gethealth();
  File "/usr/local/lib/python3.5/dist-packages/pybitflyer/pybitflyer.py", line 165, in gethealth
    return self.request(endpoint, params=params)
  File "/usr/local/lib/python3.5/dist-packages/pybitflyer/pybitflyer.py", line 60, in request
    content = json.loads(response.content.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mayabaha** [comment]
JSONDecodeErrorが発生した場合、取引所ステータスをAbnormalとみなすようにする
